create table developers (
                            id serial primary key ,
                            first_name VARCHAR(50),
                            last_name VARCHAR(50),
                            email VARCHAR(50),
                            gender VARCHAR(50),
                            country VARCHAR(50),
                            salary  INT,
                            age INT,
                            working_year DATE
);
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Danya', 'Janway', 'djanway0@ibm.com', 'Male', 'China', 12704, 27, '2002-09-29');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Sibyl', 'Everest', 'severest1@linkedin.com', 'Male', 'Nigeria', 47774, 55, '2021-11-05');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Colline', 'Ondrusek', 'condrusek2@imgur.com', 'Female', 'China', 20287, 76, '2002-03-28');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Josiah', 'McShane', 'jmcshane3@dyndns.org', 'Male', 'China', 25442, 21, '2012-11-23');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Ailbert', 'Tarburn', 'atarburn4@zdnet.com', 'Male', 'Indonesia', 14180, 61, '2000-09-25');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Gram', 'Bousfield', 'gbousfield5@weibo.com', 'Male', 'France', 28549, 20, '2017-04-01');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Nadeen', 'Igoe', 'nigoe6@illinois.edu', 'Female', 'Russia', 48217, 21, '2018-01-11');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Jenelle', 'Ellse', 'jellse7@newyorker.com', 'Female', 'Qatar', 41476, 46, '2000-03-13');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Eolande', 'Grzeszczak', 'egrzeszczak8@ft.com', 'Female', 'China', 13600, 42, '2009-04-12');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Nero', 'Moatt', 'nmoatt9@rediff.com', 'Male', 'Iran', 30138, 58, '2022-11-23');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Noelani', 'cornhill', 'ncornhilla@about.me', 'Female', 'Canada', 25167, 39, '2003-08-12');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Ulysses', 'Bullas', 'ubullasb@ocn.ne.jp', 'Male', 'Thailand', 19724, 48, '2016-06-14');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Cecil', 'Bohling', 'cbohlingc@yale.edu', 'Female', 'Netherlands', 44481, 79, '2001-11-23');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Avril', 'Downage', 'adownaged@latimes.com', 'Female', 'Brazil', 37359, 52, '1996-04-24');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Rita', 'Crankhorn', 'rcrankhorne@yellowpages.com', 'Female', 'China', 12679, 57, '2019-02-05');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Lauren', 'De Clairmont', 'ldeclairmontf@abc.net.au', 'Female', 'Indonesia', 46721, 48, '2004-01-06');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Briant', 'Hultberg', 'bhultbergg@springer.com', 'Male', 'China', 15030, 64, '2019-08-20');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Eli', 'Laughnan', 'elaughnanh@addthis.com', 'Male', 'Turkmenistan', 28332, 21, '2006-06-02');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Minetta', 'Culross', 'mculrossi@ucsd.edu', 'Female', 'Indonesia', 1279, 68, '2004-03-30');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Lyn', 'Lett', 'llettj@weebly.com', 'Non-binary', 'Russia', 35206, 62, '1995-05-06');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Bayard', 'Twinborough', 'btwinboroughk@example.com', 'Male', 'Czech Republic', 44476, 76, '2003-12-13');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Alethea', 'Flintiff', 'aflintiffl@dyndns.org', 'Agender', 'Paraguay', 48035, 30, '2011-11-25');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Lyndell', 'Gebbe', 'lgebbem@vistaprint.com', 'Genderqueer', 'Bolivia', 8976, 17, '2017-02-26');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Kenneth', 'Raun', 'kraunn@mapquest.com', 'Male', 'Laos', 1497, 57, '2012-04-15');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Skippie', 'Muldrew', 'smuldrewo@hao123.com', 'Male', 'Indonesia', 12671, 41, '2006-02-04');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Alix', 'Dunn', 'adunnp@soup.io', 'Female', 'Mongolia', 11193, 63, '2000-02-17');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Nana', 'Twede', 'ntwedeq@exblog.jp', 'Female', 'Sweden', 8667, 39, '2014-01-02');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Hannie', 'Mahy', 'hmahyr@last.fm', 'Female', 'China', 18413, 25, '2007-11-06');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Caz', 'Kalinke', 'ckalinkes@ezinearticles.com', 'Male', 'Argentina', 5181, 66, '1999-08-23');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Lalo', 'Duinkerk', 'lduinkerkt@cbsnews.com', 'Male', 'France', 40314, 33, '2000-04-07');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Dugald', 'Rabl', 'drablu@theglobeandmail.com', 'Male', 'China', 28258, 47, '2017-12-20');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Lanny', 'Birkwood', 'lbirkwoodv@gnu.org', 'Male', 'Poland', 46756, 29, '2009-07-02');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Symon', 'Barsam', 'sbarsamw@hugedomains.com', 'Male', 'Nigeria', 23087, 56, '2009-10-11');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Valentine', 'Jochanany', 'vjochananyx@mashable.com', 'Female', 'China', 17409, 48, '2022-04-18');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Lefty', 'Belli', 'lbelliy@upenn.edu', 'Male', 'Bulgaria', 31745, 63, '2006-03-09');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Bordie', 'Keetley', 'bkeetleyz@tiny.cc', 'Male', 'China', 46387, 47, '2012-05-04');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Liva', 'Beldom', 'lbeldom10@dropbox.com', 'Female', 'China', 2284, 18, '2017-09-20');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Vale', 'Fassbindler', 'vfassbindler11@utexas.edu', 'Male', 'Hungary', 14905, 68, '2022-05-03');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('El', 'Benbrick', 'ebenbrick12@indiegogo.com', 'Polygender', 'Peru', 9414, 28, '2014-12-26');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Estrellita', 'Grove', 'egrove13@163.com', 'Female', 'China', 16459, 58, '1998-04-02');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Esra', 'Bernardino', 'ebernardino14@blogger.com', 'Male', 'Canada', 19129, 18, '2002-03-27');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Swen', 'Freschini', 'sfreschini15@skype.com', 'Male', 'Peru', 1065, 22, '1997-04-04');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Reiko', 'Cuddehy', 'rcuddehy16@chron.com', 'Female', 'Serbia', 32127, 69, '2013-10-05');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Meagan', 'Willcocks', 'mwillcocks17@hostgator.com', 'Female', 'Russia', 41336, 39, '2009-06-27');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Laurice', 'Cosin', 'lcosin18@thetimes.co.uk', 'Female', 'China', 18714, 47, '2002-08-27');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Cris', 'Wildish', 'cwildish19@ocn.ne.jp', 'Male', 'Japan', 37002, 30, '2013-04-10');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Agustin', 'Thackston', 'athackston1a@issuu.com', 'Male', 'Philippines', 24199, 71, '2020-01-29');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Jamal', 'Wesker', 'jwesker1b@tuttocitta.it', 'Male', 'Brazil', 42480, 43, '2003-06-15');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Chloris', 'Player', 'cplayer1c@berkeley.edu', 'Female', 'China', 23933, 76, '2008-11-05');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Jessamine', 'Domenc', 'jdomenc1d@multiply.com', 'Female', 'Indonesia', 3289, 24, '2009-04-21');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Editha', 'Fausset', 'efausset1e@marketwatch.com', 'Non-binary', 'China', 4007, 29, '2017-10-29');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Natassia', 'Heersema', 'nheersema1f@walmart.com', 'Female', 'China', 47693, 27, '2003-04-04');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Franzen', 'Alger', 'falger1g@microsoft.com', 'Male', 'Russia', 42256, 46, '2015-12-30');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Tyson', 'Rozzier', 'trozzier1h@reddit.com', 'Male', 'Philippines', 1529, 68, '2006-03-04');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Dur', 'Bellow', 'dbellow1i@icio.us', 'Male', 'Sweden', 25585, 17, '2012-09-06');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Mikey', 'Maginn', 'mmaginn1j@seattletimes.com', 'Male', 'Israel', 47940, 28, '1996-12-02');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Debera', 'Rolf', 'drolf1k@google.pl', 'Female', 'Thailand', 49508, 18, '2020-12-26');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Jule', 'McGinley', 'jmcginley1l@adobe.com', 'Male', 'Indonesia', 22892, 61, '1998-02-03');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Dannie', 'Gueinn', 'dgueinn1m@domainmarket.com', 'Male', 'Russia', 25491, 61, '2015-08-19');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Mickie', 'Giddens', 'mgiddens1n@home.pl', 'Bigender', 'United States', 14402, 63, '2009-08-09');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Verena', 'Plowes', 'vplowes1o@twitter.com', 'Female', 'Finland', 5634, 54, '2016-05-23');
insert into developers (first_name, last_name, email, gender, country, salary , age, working_year) values ('Malvina', 'Pietruszka', 'mpietruszka1p@buzzfeed.com', 'Female', 'Indonesia', 10107, 39, '1998-12-27');

select * from developers;
--  Выберите из таблицы developers записи с id равным 3, 5, 6, 10 и логином, равным 'eee', 'zzz' или 'ggg'.
select * from developers where id in(3,5,6,10) and email in ('nmoatt9@rediff.com') ;
-- Задача. Выберите из таблицы developers записи c зарплатой от 500 до 1500.
SELECT * from developers where salary between 500 and 1500;
-- Задача. Выберите из таблицы developers все записи так, чтобы вместо id было developersId, вместо login – developersLogin, вместо salary - developersSalary.
select id as developersId,email AS developersEmail, salary as developersSalary from developers;
-- Найдите в таблице developers минимальный возраст.
select min(age) from developers ;
-- Задача. Найдите в таблице developers суммарный возраст.
select sum(age) from developers;
-- Задача. Вставьте в таблицу developers запись с полем date с текущим моментом времени в формате 'год-месяц-день часы:минуты:секунды'.

-- Задача. Вставьте в таблицу developers запись с полем date с текущей датой в формате 'год-месяц-день'.

-- Задача. При выборке из таблицы developers запишите день, месяц и год в отдельные поля.

-- На BETWEEN
-- Выберите из таблицы developers записи c зарплатой от 1000 до 3000.i98
select * from developers where salary between 1000 and 3000.98;
-- Выберите из таблицы developers записи c id от 3 до 10 и зарплатой от 300 до 500.
select * from developers where id between 3 and 10 and salary between 300 and 500;
-- На AS
-- Выберите из таблицы developers все записи так, чтобы вместо id был
select * from developers as id;
-- На DISTINCT
-- Выберите из таблицы developers все записи так, чтобы туда попали только записи с разной зарплатой (без дублей).
select distinct(salary) from developers ;
-- Получите SQL запросом все возрасты без дублирования.
select avg(age) from developers;
-- На MIN и MAX
-- Найдите в таблице developers минимальную зарплату.
select min(salary) from developers;
-- Найдите в таблице developers максимальную зарплату.
select max(salary) from developers;
-- На SUM
--  Найдите в таблице workers суммарную зарплату.
select sum(working_year) from developers;
--  Найдите в таблице developers суммарную зарплату для людей в возрасте от 21 до 25.
select sum(salary)from developers where age between 21 and 25;
--  Найдите в таблице developers суммарную зарплату для id, равного 1, 2, 3 и 5.
select sum(salary) from developers where id in(1,2,3,5);
--  На AVG
--  Найдите в таблице developers среднюю зарплату.
select avg(salary) from developers;
--  Найдите в таблице workers средний возраст.
select avg(age) from developers;
--  При выборке из таблицы workers получите первые 5 символов поля description. Показать решение.
select left(email,5) from developers;
--  При выборке из таблицы workers получите последние 5 символов поля description. Показать решение.
select right(email,5) from developers;
--  При выборке из таблицы workers получите из поля description символы со второго по десятый. Показать решение.
select substring(email, 2,10) from developers;

-- SORTED


